# ARM64 환경용 자동 생성 설정

services:
  yocto-lecture:
    platform: linux/arm64
    environment:
      - BB_NUMBER_THREADS=8
      - PARALLEL_MAKE=-j 8
      - MACHINE=qemux86-64
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - TZ=Asia/Seoul
    volumes:
      - ./yocto-workspace/workspace:/workspace
      - ./yocto-workspace/downloads:/opt/yocto/downloads
      - ./yocto-workspace/sstate-cache:/opt/yocto/sstate-cache

  yocto-lecture-dev:
    platform: linux/arm64
    environment:
      - BB_NUMBER_THREADS=8
      - PARALLEL_MAKE=-j 8
      - MACHINE=qemux86-64
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - TZ=Asia/Seoul
